version: "3.8"
services:
  postgres:
    image: postgres:16.1-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: building_control_user
      POSTGRES_PASSWORD: building_control_password
      POSTGRES_DB: building_control
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
